import sql from 'mssql'; import { getPool } from '../config/database'; import { authConfig, quoteIdentifier } from '../config/auth'; import { Role } from '../types/auth';
export interface ManagedUser { nip: string; name: string; role: Role; isActive: boolean; }
const access = () => quoteIdentifier(authConfig.accessTable);
const hris = () => quoteIdentifier(authConfig.hrisTable);
const active = () => quoteIdentifier(authConfig.hrisActiveColumn);
const nipCol = () => quoteIdentifier(authConfig.hrisNipColumn);
const nameCol = () => quoteIdentifier(authConfig.hrisNameColumn);
export async function getAccess(nip: string) { const r = await (await getPool()).request().input('nip', sql.VarChar(50), nip).query(`SELECT Role AS role, IsActive AS isActive FROM ${access()} WHERE NIP=@nip`); const x=r.recordset[0] as any; return x ? { role: String(x.role).toUpperCase() as Role, isActive: Boolean(x.isActive) } : undefined; }
export async function listAccess(): Promise<ManagedUser[]> { const r=await (await getPool()).request().query(`SELECT a.NIP AS nip,h.${nameCol()} AS name,a.Role AS role,a.IsActive AS isActive FROM ${access()} a LEFT JOIN ${hris()} h ON h.${nipCol()}=a.NIP ORDER BY h.${nameCol()}`); return r.recordset.map((x:any)=>({nip:String(x.nip).trim(),name:String(x.name??'').trim(),role:String(x.role).toUpperCase() as Role,isActive:Boolean(x.isActive)})); }
export async function searchActiveEmployees(search='') { const value=search.trim(); const r=await (await getPool()).request().input('search',sql.NVarChar(100),value).input('likeSearch',sql.NVarChar(110),`%${value}%`).query(`SELECT TOP (50) ${nipCol()} AS nip,${nameCol()} AS name FROM ${hris()} WHERE ${active()} IN ('1','Y','TRUE') AND (@search='' OR ${nipCol()} LIKE @likeSearch OR ${nameCol()} LIKE @likeSearch) ORDER BY ${nameCol()}`); return r.recordset.map((x:any)=>({nip:String(x.nip).trim(),name:String(x.name??'').trim()})); }
export async function grantAccess(nip:string,role:Role) { const r=await (await getPool()).request().input('nip',sql.VarChar(50),nip).query(`SELECT TOP (1) 1 AS found FROM ${hris()} WHERE ${nipCol()}=@nip AND ${active()} IN ('1','Y','TRUE')`); if(!r.recordset.length) throw Object.assign(new Error('Karyawan HRIS tidak aktif atau tidak ditemukan.'),{status:400}); await (await getPool()).request().input('nip',sql.VarChar(50),nip).input('role',sql.VarChar(30),role).query(`MERGE ${access()} AS t USING (SELECT @nip AS NIP,@role AS Role) AS s ON t.NIP=s.NIP WHEN MATCHED THEN UPDATE SET Role=s.Role,IsActive=1,UpdatedAt=SYSDATETIME() WHEN NOT MATCHED THEN INSERT(NIP,Role,IsActive) VALUES(s.NIP,s.Role,1);`); }
export async function updateAccess(nip:string,input:{role?:Role;isActive?:boolean}) { const fields=['UpdatedAt=SYSDATETIME()']; const r=(await getPool()).request().input('nip',sql.VarChar(50),nip); if(input.role){fields.push('Role=@role');r.input('role',sql.VarChar(30),input.role);} if(typeof input.isActive==='boolean'){fields.push('IsActive=@isActive');r.input('isActive',sql.Bit,input.isActive);} await r.query(`UPDATE ${access()} SET ${fields.join(',')} WHERE NIP=@nip`); }
